meta:
  id: nx_store_data
  application: |
    Mii data format used on the Switch via the nn::mii library,
    also used in Miitomo >= 2.3.0, and potentially used in
    mobile games in Unity (CoreDataConverter.dll path found in Pikmin Bloom).
    Bitfield packed representation of nn::mii::CharInfo.
  file-extension:
    # Unofficial:
    - nfcd
    - nfsd
  xref:
    struct_names: |
      nn::mii::CoreData/nn::mii::StoreData
      nn::mii::detail::CoreDataRaw/nn::mii::detail::StoreDataRaw
  endian: le
  bit-endian: le

seq:
  - id: hair_type
    type: u1
  - id: height
    type: b7
  - id: mole_type
    type: b1
  - id: build
    type: b7
  - id: hair_flip
    type: b1
  - id: hair_color
    type: b7
  - id: type
    type: b1
  - id: eye_color
    type: b7
  - id: gender
    type: b1
  - id: eyebrow_color
    type: b7
  - id: pad_0
    type: b1
  - id: mouth_color
    type: b7
  - id: pad_1
    type: b1
  - id: beard_color
    type: b7
  - id: pad_2
    type: b1
  - id: glass_color
    type: b7
  - id: pad_3
    type: b1
  - id: eye_type
    type: b6
  - id: region_move
    type: b2
    enum: region_move
  - id: mouth_type
    type: b6
  - id: font_region
    type: b2
    enum: font_region
  - id: eye_y
    type: b5
  - id: glass_scale
    type: b3
  - id: eyebrow_type
    type: b5
  - id: mustache_type
    type: b3
  - id: nose_type
    type: b5
  - id: beard_type
    type: b3
  - id: nose_y
    type: b5
  - id: mouth_aspect
    type: b3
  - id: mouth_y
    type: b5
  - id: eyebrow_aspect
    type: b3
  - id: mustache_y
    type: b5
  - id: eye_rotate
    type: b3
  - id: glass_y
    type: b5
  - id: eye_aspect
    type: b3
  - id: mole_x
    type: b5
  - id: eye_scale
    type: b3
  - id: mole_y
    type: b5
  - id: pad_4
    type: b3
  - id: glass_type
    type: b5
  - id: pad_5
    type: b3
  - id: favorite_color
    type: b4
  - id: faceline_type
    type: b4
  - id: faceline_color
    type: b4
  - id: faceline_wrinkle
    type: b4
  - id: faceline_make
    type: b4
  - id: eye_x
    type: b4
  - id: eyebrow_scale
    type: b4
  - id: eyebrow_rotate
    type: b4
  - id: eyebrow_x
    type: b4
  - id: eyebrow_y
    type: b4
    doc: Value + 3 = true value.
  - id: nose_scale
    type: b4
  - id: mouth_scale
    type: b4
  - id: mustache_scale
    type: b4
  - id: mole_scale
    type: b4

  - id: nickname
    type: str
    encoding: UTF-16LE
    size: 20
    doc: |
      Does not contain a null terminator at the end.
      NOTE that in order for this to be valid,
      it CANNOT contain any characters after the first
      null terminator character. (nn::mii::Nickname::IsValid() -> IsContinuityTermination(unsigned short const *, int))
    if: not _io.eof

# TODO TODO TODO DOCS
  - id: create_id
    type: create_id  # struct nn::mii::CreateId
    #type: u1
    #repeat: expr
    #repeat-expr: 16
    if: not _io.eof

  - id: crc16
    type: u2
    if: not _io.eof
  - id: crc16_device
    type: u2
    if: not _io.eof

# Mirror fields based on naming
# used in other structures.
instances:
  # nn::mii naming:
  face_color:
    value: faceline_color
  face_type:
    value: faceline_type
  face_tex:
    value: faceline_wrinkle
  beard_scale:
    value: mustache_scale
  beard_y:
    value: mustache_y
  name:
    value: nickname

# Expand CreateID type to add validation.
types:
  create_id:
    seq:
      - id: data
        doc: |
          This is struct nn::mii::CreateId, which contains nn::util::Uuid (UUIDv4)
          generated by: struct nn::util::Uuid __cdecl nn::util::`anonymous namespace'::GenerateUuidVersion4(void)
          NOTE that this cannot just be completely random in order to be valid (see is_valid)
          To make a valid CreateID, set the following: `data[8] &= 0x3f; data[8] |= 0x80;`
          Optionally to be a valid UUIDv4 as well: `data[6] &= & 0x0f; data[6] |= 0x40;`
        type: u1
        repeat: expr
        repeat-expr: 16
    instances:
      is_valid:
        value: |
          (data[8] & 0b11000000) == 0b10000000
        doc: |
          Checks the two leftmost bits of byte 8 ("clock_seq_hi_and_reserved" field in RFC 4122)
          that are verified by nn::mii::CreateId::IsValid().
          If this is false, this Mii will not be valid on a real Switch.

enums:
  region_move:    # CFLiRegionMove
    0: all
    1: jp_only
    2: us_only
    3: eu_only
  font_region:    # CFLFontRegion/FFLFontRegion/nn::mii::FontRegion
    0: jp_us_eu
    1: china
    2: korea
    3: taiwan
  gender:         # CFLGender/FFLGender/nn::mii::Gender
    0: male
    1: female
    2: all
  favorite_color: # CFLFavoriteColor/FFLFavoriteColor/nn::mii::FavoriteColor
    0: red
    1: orange
    2: yellow
    3: yellowgreen
    4: green
    5: blue
    6: skyblue
    7: pink
    8: purple
    9: brown
    10: white
    11: black
  type:           # nn::mii::MiiType
    0: normal
    1: special
